Homework #11 - strings - main task
kirill-zavelev/teachmeskills_hometasks pull request #5
Opened 2023-01-15 20:45 UTC by kirill-zavelev

2023-01-15 21:14 UTC, testershmester requested changes
см комментарии

2023-01-15 21:14 UTC, testershmester commented on src/by/teachmeskills/strings/StringValidation.java
> +            String newDocument = document.replaceAll("-[a-zA-Z]{3}", "");
можно вынести повторяющиеся паттерны как константы

2023-01-15 21:14 UTC, testershmester commented on src/by/teachmeskills/strings/StringValidation.java
> +        return documentWithoutDigits;
yyy/yyy/y/y должен быть, не хватает еще слеша в конце

2023-01-15 21:14 UTC, testershmester commented on src/by/teachmeskills/strings/StringValidation.java
> +            System.out.println(INCORRECT_DOCUMENT_FORMAT_MSG);
![image](https://user-images.githubusercontent.com/29692064/212567539-34cd5bde-2c2f-4d44-8d7d-f870bc7fdd55.png)
yyy/yyy/y/y

2023-01-15 21:14 UTC, testershmester commented on src/by/teachmeskills/strings/StringValidation.java
> +                    .matches("^" + Pattern.compile(document.substring(0, 1)) + "{3,}");
regex хорошо, но проще просто привести строку к нижнему регистру и проверить abc

2023-01-16 09:22 UTC, kirill-zavelev commented on src/by/teachmeskills/strings/StringValidation.java
> +                    .matches("^" + Pattern.compile(document.substring(0, 1)) + "{3,}");
@testershmester спасибо за комментарий, есть уточнение по требованиям - ожидаем ли мы по заданию проверку строки на:

1. Совпадение на наличие **именно** "abc"  в любом месте строки?
2. Совпадение на наличие **именно** "555" в начале строки?
3. Совпадение на наличие **именно** "1a2b" в конце строки?

2023-01-17 19:15 UTC, kirill-zavelev commented on src/by/teachmeskills/strings/StringValidation.java
> +            String newDocument = document.replaceAll("-[a-zA-Z]{3}", "");
Исправлено в [коммите](https://github.com/kirill-zavelev/teachmeskills_hometasks/pull/5/commits/eff13272d61b9bf0c7cefce6abdd15a36042dd3e)

2023-01-17 19:16 UTC, kirill-zavelev commented on src/by/teachmeskills/strings/StringValidation.java
> +        return documentWithoutDigits;
Исправлено в [новом коммите](https://github.com/kirill-zavelev/teachmeskills_hometasks/pull/5/commits/eff13272d61b9bf0c7cefce6abdd15a36042dd3e)

2023-01-17 19:16 UTC, kirill-zavelev commented on src/by/teachmeskills/strings/StringValidation.java
> +            System.out.println(INCORRECT_DOCUMENT_FORMAT_MSG);
Исправлено в [новом коммите](https://github.com/kirill-zavelev/teachmeskills_hometasks/pull/5/commits/eff13272d61b9bf0c7cefce6abdd15a36042dd3e)

2023-01-17 19:18 UTC, kirill-zavelev commented on src/by/teachmeskills/strings/StringValidation.java
> +                    .matches("^" + Pattern.compile(document.substring(0, 1)) + "{3,}");
Неправильно понял требование, исправлено в [новом коммите](https://github.com/kirill-zavelev/teachmeskills_hometasks/pull/5/commits/eff13272d61b9bf0c7cefce6abdd15a36042dd3e) без регулярных выражений при помощи startsWith(), endsWith(), contains()

2023-01-25 17:39 UTC, testershmester approved these changes
ok

2023-01-25 17:39 UTC, testershmester commented on src/by/teachmeskills/strings/StringValidation.java
> +                    + ANY_DIGIT_REGEX
регулярное выражение в константе лучше хранить целиком, иначе тяжело воспринимается и нельзя быстро проверить регулярку в стороннем сервисе

2023-02-03 09:20 UTC, merged