Homework #12 - collections
kirill-zavelev/teachmeskills_hometasks pull request #6
Opened 2023-01-22 12:10 UTC by kirill-zavelev

2023-01-22 12:45 UTC, testershmester requested changes
см комментарии

2023-01-22 12:45 UTC, testershmester commented on src/by/teachmeskills/collections/BoxDemo.java
> +        Set<Ball> balls = Stream.of(new Ball(10), new Ball(20), new Ball(30)).collect(Collectors.toSet());
Set.of() вместо Stream.of

2023-01-22 12:45 UTC, testershmester commented on src/by/teachmeskills/collections/BoxDemo.java
> +        Set<Ball> balls = Stream.of(new Ball(10), new Ball(20), new Ball(30)).collect(Collectors.toSet());
Stream.of нужен только тогда, когда нужно получить stream, для всего остального есть уже специальные методы

2023-01-22 12:45 UTC, testershmester commented on src/by/teachmeskills/collections/Container.java
> +        new HashSet<>(balls);
сет создается в пустоту

2023-01-22 12:45 UTC, testershmester commented on src/by/teachmeskills/collections/Container.java
> +        new HashSet<>(balls);
this.balls.addAll(balls);
только предварительно убедиться, что this.balls не null

2023-01-22 12:45 UTC, testershmester commented on src/by/teachmeskills/collections/Container.java
> +    public void getBallsAmount(Set<Ball> balls) {
в каждом методе Set<Ball> добавлен как параметр, но зачем? ведь он уже хранится внутри контейнера

2023-01-22 12:45 UTC, testershmester commented on src/by/teachmeskills/collections/Container.java
> +        this.balls = balls;
в контейнер должен поместиться пустой сет один раз при создании. дальше вот такая конструкция не должна использоваться (присваивание) ,только модификация

2023-01-22 12:45 UTC, testershmester commented on src/by/teachmeskills/collections/Container.java
> +        boolean matches = Stream.of(balls).anyMatch(b -> balls.contains(ball));
` boolean matches = this.balls.stream()
                                    .anyMatch(b -> balls.contains(ball));`

2023-01-22 12:59 UTC, testershmester commented on src/by/teachmeskills/collections/Box.java
> +public class Box extends Container {
размер ящика?

2023-01-22 12:59 UTC, testershmester commented on src/by/teachmeskills/collections/Box.java
> +
метод должен возвращать отсортированный список

2023-01-22 18:08 UTC, kirill-zavelev commented on src/by/teachmeskills/collections/Box.java
> +public class Box extends Container {
@testershmester размер ящика контролируется в конструкторе Box(), где вызывается метод isSetHasMax10Balls(), который проверяет размер сета balls и, в случае размера < 10 элементов, происходит добавление шара. Как можно указать размер ящика другим способом?

```
public Box(Set<Ball> balls) {
        if (isSetHasMax10Balls(balls)) {
            addBalls(balls);
            this.balls = balls;
        }
    }
```

2023-01-22 18:10 UTC, kirill-zavelev commented on src/by/teachmeskills/collections/Box.java
> +
@testershmester а почему список? Данный метод служит для проверки кол-ва уже имеющихся элементов в сете и вызывается в дальнейшем в конструкторе (где сами элементы добавляются/не добавляются)

2023-01-22 18:29 UTC, kirill-zavelev commented on src/by/teachmeskills/collections/Container.java
> +    public void getBallsAmount(Set<Ball> balls) {
@testershmester правильно ли я понял: сет шаров должен инициализироваться в конструкторе по типу 

```
public Container() {
        this.balls = new HashSet<>();
    }
```

и затем в методах использовать this.balls везде, вместо добавленного параметра Set?

2023-01-22 19:01 UTC, testershmester commented on src/by/teachmeskills/collections/Container.java
> +    public void getBallsAmount(Set<Ball> balls) {
Именно

2023-01-22 19:02 UTC, testershmester commented on src/by/teachmeskills/collections/Box.java
> +public class Box extends Container {
В задании вроде сказано, что размер должен задаваться при создании ящика, т.е. через конструктор

2023-01-22 19:04 UTC, testershmester commented on src/by/teachmeskills/collections/Box.java
> +
По заданию метод должен что-то возвращать. HashSet не хранит порядок, поэтому я и написала лист в качестве примера. Можно сразу в три сете например хранить

2023-01-22 19:09 UTC, kirill-zavelev commented on src/by/teachmeskills/collections/Box.java
> +public class Box extends Container {
С помощью initialCapacity=10? То есть инициализировать Set в конструкторе по типу this.balls = new HashSet(10)?

2023-01-25 17:40 UTC, testershmester approved these changes
cool

2023-02-03 09:20 UTC, merged